import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";
import "./globals.css"; 
import Header from "./components/Header";
import Navigation from "./components/Navbar";
import {Footer} from "./components/Footer";
import { CartProvider } from "./components/cart/cart-context";
import { cookies } from "next/headers";
import { getCart } from "./lib/shopify";
import SizeGuide from "./components/SizeGuide";
const darkerGrotesque = Darker_Grotesque({
  subsets: ["latin"], // Supports Latin characters
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Select font weights
  variable: "--font-darker-grotesque", // Define a CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type FooterSection = {
  title: string;
  links: Array<{
    label: string;
    href: string;
  }>;
}

// Updated footer sections with proper links
const footerSections: FooterSection[] = [
  {
    title: "concierge",
    links: [
      { label: "contact", href: "/contact" },
      { label: "size & fit", href: "/size-guide" },
      { label: "track an order", href: "/order-tracking" },
      { label: "shipping & delivery", href: "/shipping" },
      { label: "account", href: "/account" },
      { label: "FAQ", href: "/faq" }
    ]
  },
  {
    title: "company",
    links: [
      { label: "who we are", href: "/about" },
      { label: "sustainability", href: "/sustainability" }
    ]
  },
  {
    title: "legal",
    links: [
      { label: "return & cancellation policy", href: "/returns" },
      { label: "accessibility policy", href: "/accessibility" },
      { label: "privacy policy", href: "/privacy" },
      { label: "terms of service", href: "/tos" },
      { label: "do not sell or share my personal data​", href: "/privacy/do-not-sell" }
    ]
  },
  {
    title: "social",
    links: [
      { label: "instagram", href: "https://instagram.com/kilaeko" },
      { label: "spotify", href: "https://spotify.com/kilaeko" },
      { label: "pinterest", href: "https://pinterest.com/kilaeko" }
    ]
  }
];

const paymentMethods = [
  "/payment/visa.svg",
  "/payment/mastercard.svg",
  "/payment/paypal.svg",
  "/payment/klarna.svg",
  "/payment/applepay.svg",
  "/payment/afterpay.svg",
  "/payment/shoppay.svg",
  "/payment/googlepay.svg",
  "/payment/amex.svg"
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cartId = (await cookies()).get("cartId")?.value;
  const cart = getCart(cartId);
  
  return (
    <html lang="en">
      <body
        className={`${darkerGrotesque.variable} antialiased`}
      ><CartProvider cartPromise={cart}>
      <Header/>
      <Navigation/>
      <SizeGuide/>
        {children}
      <Footer sections={footerSections} paymentMethods={paymentMethods} />
      </CartProvider>
      </body>
    </html>
  );
}
